### PR TITLE
Update abstract factory hw

### PR DESCRIPTION
**Pull request by dyc3**
- update doughs
- update pizza toString
- add cheese classes
- add pepperoni classes
- add clams classes
- add veggies classes
- update ingredient factories
- add a bunch of toString impls
- tweak PizzaStore class
- update diagram

### CODE REVIEW

**Review by evanciok — COMMENTED** [review]
add sequence diagram for ordering a specific pizza type

**Comment by evanciok** [comment]
```mermaid
sequenceDiagram
    actor User
    User->>PizzaStoreFactory: order NY veggie pizza
    activate User
    activate PizzaStoreFactory
    PizzaStoreFactory->>NYPizzaStore: create NY franchise
    activate NYPizzaStore
    deactivate PizzaStoreFactory 
    NYPizzaStore->>Pizza: create pizza
    activate Pizza
    NYPizzaStore->>NYPizzaIngredientFactory: instantiate concrete factory
    deactivate NYPizzaStore
    activate NYPizzaIngredientFactory
    NYPizzaIngredientFactory->>Ingredients: instantiate NY ingredients
    deactivate NYPizzaIngredientFactory
    activate Ingredients
    Pizza->>NYVeggiePizza: prepare pizza
    deactivate Pizza
    activate NYVeggiePizza
    Ingredients->>NYVeggiePizza: add dough, sauce, cheese, veggies
    deactivate Ingredients 
    NYVeggiePizza-->>User: return product
    deactivate NYVeggiePizza
    deactivate User
```

**Comment by dyc3** [comment]
This doesn't seem right. `Pizza` should be `NYVeggiePizza`, which then uses the ingredient factory to make the ingredients.

Also the activation bars don't look right either.

**Comment by sophiadicuffa** [comment]
```mermaid
sequenceDiagram
    actor User
    participant PizzaStoreFactory
    participant NYPizzaStore
    participant NYPizzaIngredientFactory
    participant Ingredients
    participant NYVeggiePizza

    User->>+PizzaStoreFactory: order NY veggie pizza
    PizzaStoreFactory->>+NYPizzaStore: create NY franchise
    NYPizzaStore->>+NYVeggiePizza: create pizza
    NYPizzaStore->>+NYPizzaIngredientFactory: instantiate concrete factory
    NYPizzaIngredientFactory->>+Ingredients: instantiate NY ingredients
    Ingredients-->>+NYVeggiePizza: add dough, sauce, cheese, veggies
    NYVeggiePizza-->>-NYPizzaStore: return pizza
    NYPizzaStore-->>-PizzaStoreFactory: return pizza
    PizzaStoreFactory-->>-User: return pizza
```

**Comment by dyc3** [comment]
I have an alternative sequence diagram that I think makes more sense given how the code is structured.

```mermaid
sequenceDiagram
    actor User
    participant Application
    participant PizzaStoreFactory
    participant NYPizzaStore
    participant NYPizzaIngredientFactory
    participant NYVeggiePizza
    participant Ingredients

    User->>+Application: order NY veggie pizza
    Application->>+PizzaStoreFactory: create NY franchise
    PizzaStoreFactory->>-Application: return NYPizzaStore
    Application->>+NYPizzaStore: createPizza()
    NYPizzaStore->>NYPizzaIngredientFactory: create ingredient factory
    NYPizzaIngredientFactory->>NYPizzaStore: 
    NYPizzaStore->>+NYVeggiePizza: create pizza
    NYVeggiePizza->>NYPizzaIngredientFactory: instantiate NY ingredients
    NYVeggiePizza->>Ingredients: apply dough, sauce, cheese, veggies
    Ingredients->>NYVeggiePizza: 
    NYVeggiePizza->>-NYPizzaStore: return pizza
    NYPizzaStore->>-Application: return NYVeggiePizza
    Application->>-User: print pizza

```

**Pull request merged**
