### PR TITLE
Abstract factory hw

### PR DESCRIPTION
**Pull request by dyc3**

### CODE REVIEW

**Review by evanciok — APPROVED** [review]

**Comment by dyc3** [comment]
Don't merge it yet, we aren't done

**Comment by dyc3** [comment]
```mermaid
classDiagram
    class Cheese
    class Clam
    class Dough
    class ThinCrustDough
    class ThickCrustDough
    Dough <|-- ThinCrustDough
    Dough <|-- ThickCrustDough
    class Pepperoni
    class Sauce
    class MarinaraSauce
    class PlumTomatoeSauce
    Sauce <|-- MarinaraSauce
    Sauce <|-- PlumTomatoeSauce
    class Veggies

    class PizzaIngredientFactory
    class NYPizzaIngredientFactory
    class ChicagoPizzaIngredientFactory
    PizzaIngredientFactory <|-- NYPizzaIngredientFactory
    PizzaIngredientFactory <|-- ChicagoPizzaIngredientFactory

    NYPizzaIngredientFactory ..> Cheese
    ChicagoPizzaIngredientFactory <..> Cheese
    NYPizzaIngredientFactory ..> Clam
    ChicagoPizzaIngredientFactory ..> Clam
    NYPizzaIngredientFactory ..> ThinCrustDough
    ChicagoPizzaIngredientFactory ..> ThickCrustDough
    NYPizzaIngredientFactory <..> Pepperoni
    ChicagoPizzaIngredientFactory ..> Pepperoni
    NYPizzaIngredientFactory ..> MarinaraSauce
    ChicagoPizzaIngredientFactory ..> PlumTomatoeSauce
    NYPizzaIngredientFactory ..> Veggies
    ChicagoPizzaIngredientFactory ..> Veggies

```

**Comment by sophiadicuffa** [comment]
cd

**Comment by sophiadicuffa** [comment]
classDiagram
    PizzaIngredientsFactory <|-- NYPizzaIngredientsFactory
    PizzaIngredientsFactory <|-- Pizza
    MarinaraSauce <.. NYPizzaIngredientsFactory
    ThinCrustDough <.. NYPizzaIngredientsFactory
    ThickCrustDough <.. ChicagoPizzaIngredientsFactory
    PlumTomatoeSauce <.. ChicagoPizzaIngredientsFactory
    PizzaIngredientsFactory <|-- ChicagoPizzaIngredientsFactory
    ThinCrustDough --|> Dough
    ThickCrustDough --|> Dough
    PlumTomatoeSauce --|> Sauce
    MarinaraSauce --|> Sauce
    Dough <-- Pizza
    Sauce <-- Pizza
    ChicagoPizzaIngredientsFactory <.. Pepperoni
    NYPizzaIngredientsFactory <.. Pepperoni
    ChicagoPizzaIngredientsFactory <.. Veggies
    NYPizzaIngredientsFactory <.. Veggies
    ChicagoPizzaIngredientsFactory <.. Cheese
    NYPizzaIngredientsFactory <.. Cheese
    ChicagoPizzaIngredientsFactory <.. Clam
    NYPizzaIngredientsFactory <.. Clam


    PizzaIngredientsFactory: + createSauce()
    PizzaIngredientsFactory: + createDough()
    PizzaIngredientsFactory: + createCheese()
    PizzaIngredientsFactory: + createVeggies()
    PizzaIngredientsFactory: + createPepperoni()
    PizzaIngredientsFactory: + createClam()
    class NYPizzaIngredientsFactory{
    + createSauce()
    + createDough()
    + createCheese()
    + createVeggies()
    + createPepperoni()
    + createClam()
    }
    class ChicagoPizzaIngredientsFactory{
    + createSauce()
    + createDough()
    + createCheese()
    + createVeggies()
    + createPepperoni()
    + createClam()
    }

**Comment by sophiadicuffa** [comment]
```classDiagram
    PizzaIngredientsFactory <|-- NYPizzaIngredientsFactory
    PizzaIngredientsFactory <|-- Pizza
    MarinaraSauce <.. NYPizzaIngredientsFactory
    ThinCrustDough <.. NYPizzaIngredientsFactory
    ThickCrustDough <.. ChicagoPizzaIngredientsFactory
    PlumTomatoeSauce <.. ChicagoPizzaIngredientsFactory
    PizzaIngredientsFactory <|-- ChicagoPizzaIngredientsFactory
    ThinCrustDough --|> Dough
    ThickCrustDough --|> Dough
    PlumTomatoeSauce --|> Sauce
    MarinaraSauce --|> Sauce
    Dough <-- Pizza
    Sauce <-- Pizza
    ChicagoPizzaIngredientsFactory <.. Pepperoni
    NYPizzaIngredientsFactory <.. Pepperoni
    ChicagoPizzaIngredientsFactory <.. Veggies
    NYPizzaIngredientsFactory <.. Veggies
    ChicagoPizzaIngredientsFactory <.. Cheese
    NYPizzaIngredientsFactory <.. Cheese
    ChicagoPizzaIngredientsFactory <.. Clam
    NYPizzaIngredientsFactory <.. Clam


    PizzaIngredientsFactory: + createSauce()
    PizzaIngredientsFactory: + createDough()
    PizzaIngredientsFactory: + createCheese()
    PizzaIngredientsFactory: + createVeggies()
    PizzaIngredientsFactory: + createPepperoni()
    PizzaIngredientsFactory: + createClam()
    class NYPizzaIngredientsFactory{
    + createSauce()
    + createDough()
    + createCheese()
    + createVeggies()
    + createPepperoni()
    + createClam()
    }
    class ChicagoPizzaIngredientsFactory{
    + createSauce()
    + createDough()
    + createCheese()
    + createVeggies()
    + createPepperoni()
    + createClam()
    }```

**Comment by sophiadicuffa** [comment]
```mermaid
classDiagram
    PizzaIngredientsFactory <|-- NYPizzaIngredientsFactory
    PizzaIngredientsFactory <|-- Pizza
    MarinaraSauce <.. NYPizzaIngredientsFactory
    ThinCrustDough <.. NYPizzaIngredientsFactory
    ThickCrustDough <.. ChicagoPizzaIngredientsFactory
    PlumTomatoeSauce <.. ChicagoPizzaIngredientsFactory
    PizzaIngredientsFactory <|-- ChicagoPizzaIngredientsFactory
    ThinCrustDough --|> Dough
    ThickCrustDough --|> Dough
    PlumTomatoeSauce --|> Sauce
    MarinaraSauce --|> Sauce
    Dough <-- Pizza
    Sauce <-- Pizza
    ChicagoPizzaIngredientsFactory <.. Pepperoni
    NYPizzaIngredientsFactory <.. Pepperoni
    ChicagoPizzaIngredientsFactory <.. Veggies
    NYPizzaIngredientsFactory <.. Veggies
    ChicagoPizzaIngredientsFactory <.. Cheese
    NYPizzaIngredientsFactory <.. Cheese
    ChicagoPizzaIngredientsFactory <.. Clam
    NYPizzaIngredientsFactory <.. Clam


    PizzaIngredientsFactory: + createSauce()
    PizzaIngredientsFactory: + createDough()
    PizzaIngredientsFactory: + createCheese()
    PizzaIngredientsFactory: + createVeggies()
    PizzaIngredientsFactory: + createPepperoni()
    PizzaIngredientsFactory: + createClam()
    class NYPizzaIngredientsFactory{
    + createSauce()
    + createDough()
    + createCheese()
    + createVeggies()
    + createPepperoni()
    + createClam()
    }
    class ChicagoPizzaIngredientsFactory{
    + createSauce()
    + createDough()
    + createCheese()
    + createVeggies()
    + createPepperoni()
    + createClam()
    }
```

**Comment by sophiadicuffa** [comment]
```mermaid
classDiagram
    class PizzaIngredientFactory {
        + createSauce()
        + createDough()
        + createCheese()
        + createVeggies()
        + createPepperoni()
        + createClam()
    }

    class NYPizzaIngredientFactory{
        + createSauce()
        + createDough()
        + createCheese()
        + createVeggies()
        + createPepperoni()
        + createClam()
    }

    class ChicagoPizzaIngredientFactory{
        + createSauce()
        + createDough()
        + createCheese()
        + createVeggies()
        + createPepperoni()
        + createClam()
    }

    class Pizza{
        + String name;
	    + Dough dough;
	    + Sauce sauce;
	    + Cheese cheese;
	    + Clam clam;
        + bake()
        + cut()
        + box()
        + preapre()
        + getName(String)
        + toString(String)
    }

    class CheesePizza{
    + prepare()
    }
    class VeggiePizza{
    + prepare()
    }
    class ClamPizza{
    + prepare()
    }
    class PepperoniPizza{
    + prepare()
    }

    PizzaIngredientFactory <|-- NYPizzaIngredientFactory
    PizzaIngredientFactory <-- Pizza
    PizzaIngredientFactory <|-- ChicagoPizzaIngredientFactory

    ThinCrustDough --|> Dough
    ThickCrustDough --|> Dough
    PlumTomatoeSauce --|> Sauce
    MarinaraSauce --|> Sauce
    Dough <-- Pizza
    Sauce <-- Pizza
    Cheese <-- Pizza
    Clam <-- Pizza
    Pepperoni <-- Pizza
    Veggies <-- Pizza


    NYPizzaIngredientFactory ..> Cheese
    ChicagoPizzaIngredientFactory ..> Cheese
    NYPizzaIngredientFactory ..> Clam
    ChicagoPizzaIngredientFactory ..> Clam
    NYPizzaIngredientFactory ..> ThinCrustDough
    ChicagoPizzaIngredientFactory ..> ThickCrustDough
    NYPizzaIngredientFactory ..> Pepperoni
    ChicagoPizzaIngredientFactory ..> Pepperoni
    NYPizzaIngredientFactory ..> MarinaraSauce
    ChicagoPizzaIngredientFactory ..> PlumTomatoeSauce
    NYPizzaIngredientFactory ..> Veggies
    ChicagoPizzaIngredientFactory ..> Veggies
    Pizza <|-- CheesePizza
    Pizza <|-- ClamPizza
    Pizza <|-- VeggiePizza
    Pizza <|-- PepperoniPizza

```

**Pull request merged**
